"""
ATBMind Plugin Data Contract Schemas
Defines core Pydantic v2 models for templates, intent drafts, and workflow steps/results.
"""

from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field

class TemplateMetadata(BaseModel):
    """
    Standard metadata definition for domain instruction/prompt templates.
    Used for local SQLite indexing and Layer 2 workflow planning.
    """
    template_id: str = Field(..., description="Unique identifier for the template, e.g. T_DRAW_0102")
    name: str = Field(..., description="Human-readable name of the template")
    category: str = Field(..., description="Domain category, e.g. body_shaping, face_detail, mesh_gen")
    keywords: List[str] = Field(default_factory=list, description="Searchable keyword tags")
    target_scope: str = Field(..., description="Target object scope: single_person, background, mesh, etc.")
    slot_definitions: Dict[str, Any] = Field(
        default_factory=dict,
        description="Definitions of configurable slots/parameters including type and default value",
    )
    dependencies: List[str] = Field(
        default_factory=list,
        description="List of template_ids that must precede this template in an execution DAG",
    )

class StructuredIntentDraft(BaseModel):
    """
    Intermediate structured representation generated by Layer 1 (Latent Intent Completer).
    Bridges raw colloquial input to canonical slot requirements.
    """
    request_id: str = Field(..., description="Traceable request ID")
    plugin_id: str = Field(..., description="Target plugin identifier, e.g. draw")
    intent_category: str = Field(..., description="Classified intent category")
    target_entities: List[Dict[str, Any]] = Field(
        default_factory=list,
        description="Entities detected in visual or textual context",
    )
    parameters: Dict[str, Any] = Field(
        default_factory=dict,
        description="Extracted or imputed parameter key-values",
    )
    plugin_payload: Optional[Dict[str, Any]] = Field(
        default=None,
        description="Optional plugin-specific domain payload (e.g. mask coordinates)",
    )

class WorkflowStep(BaseModel):
    """
    Single step within an execution workflow DAG planned by Layer 2.
    """
    step: int = Field(..., description="Step sequence index (1-based)")
    template_id: str = Field(..., description="Selected template ID to execute")
    name: str = Field(..., description="Name of this workflow step")
    slots: Dict[str, Any] = Field(
        default_factory=dict,
        description="Bound parameter slots for this step execution",
    )

class WorkflowResult(BaseModel):
    """
    Result returned by a plugin after executing a WorkflowStep.
    """
    step: int = Field(..., description="Step sequence index corresponding to the step executed")
    success: bool = Field(..., description="Whether the step executed successfully")
    output_data: Dict[str, Any] = Field(
        default_factory=dict,
        description="Output artifacts, metadata, or rendered assets",
    )
    execution_time_ms: float = Field(0.0, description="Execution duration in milliseconds")
    error_message: Optional[str] = Field(default=None, description="Error message if step failed")

class WorkflowPlan(BaseModel):
    """
    Complete workflow execution plan generated by Layer 2 (WorkflowPlanner).
    """
    request_id: str = Field(..., description="Traceable request ID")
    plugin_id: str = Field(..., description="Target plugin identifier")
    steps: List[WorkflowStep] = Field(
        default_factory=list,
        description="Topologically sorted workflow steps",
    )

